force_cast: error
force_try: error

excluded:
  - Carthage
  - Pods

line_length: 100
line_length:
  warning: 110
  error: 120

type_name:
  min_length: 4
  max_length:
    warning: 30
    error: 40
  excluded:
    - id
